#!/bin/sh
set -euf
read -r status < /sys/class/power_supply/BAT0/status
read -r capacity < /sys/class/power_supply/BAT0/capacity

case "$status" in
	Discharging)
		if [ "$capacity" -le 10 ]; then
			notify-send -u critical "${capacity}% battery"
		elif [ "$capacity" -le 20 ]; then
			notify-send "${capacity}% battery"
		fi
		;;
	Charging)
		if [ "$capacity" -ge 80 ]; then
			notify-send -u low "${capacity}% battery"
		fi
		;;
esac

