#!/usr/bin/env python3
import fileinput
import sys


def readin():
    t = [line for line in fileinput.input() if line != "\n"]
    return t


def lensort(t):
    t.sort(key=lambda item: (-len(item), item), reverse=True)
    for line in t:
        sys.stdout.write(line)


if __name__ == '__main__':
    wordlist = readin()
    lensort(wordlist)
