#!/bin/sh

# Check a webpage for a string
if ping -c 1 -n -q www.ucol.ac.nz >/dev/null 2>&1; then
   if curl -s "$url" | grep -i "We're taking the step of postponing driver testing" >/dev/null; then
       notify-send -u critical "Check out $url now!"
   fi
else
    notify-send "Not online so couldn't $0"
fi
