#!/usr/bin/env bash
set -euf
cd ~/.config/hosts || exit 1
otherdir="${HOME}/git/blocklists/corporations/"
wget 'https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts' -O ~/.config/hosts/stevenblackhosts

cat stevenblackhosts "${otherdir}"{apple/all,facebook/instagram,pinterest/all,twitter/all} blacklist > etchosts

# while read -r line; do
#     sed -i "/^0.0.0.0 ${line}$/d" etchosts
# done < whitelist
